import Head from "next/head";
import Image from "next/image";
// import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="hero">
          <div id="hero"></div>
          <div className="container">
            <div className="row justify-content-center">
              <div className="col-lg-8">
                <div className="hero-content">
                  <h1>Boost Sales & Earn Customers for life with Leading Salesforce Partner</h1>
                  <p>Salesforce CRM: Scale Faster, Grow Better</p>
                  <a href="" className="btn btn-prime">Request a Free Demo</a>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="m-mines">
          <div className="container">
            <div className="row justify-content-center">
              <div className="col-lg-9">
                <div className="banner-pic-flot">
                  <figure className="main-pic">
                    <img src="/img/banner/home-main-banner.png" className="pc-cenetr" alt="home-main-banner" />
                  </figure>
                  <figure className="main-pi-abso main-pic-1">
                    <img src="/img/section/float-left-1.png" className="pc-cenetr" alt="float-left" />
                  </figure>
                  <figure className="main-pi-abso main-pic-2">
                    <img src="/img/section/float-left-2.png" className="pc-cenetr" alt="float-left" />
                  </figure>
                  <figure className="main-pi-abso main-pic-3">
                    <img src="/img/section/float-left-3.png" className="pc-cenetr" alt="float-left" />
                  </figure>
                  <figure className="main-pi-abso main-pic-4">
                    <img src="/img/section/float-left-4.png" className="pc-cenetr" alt="float-left" />
                  </figure>
                  <figure className="main-pi-abso main-pic-5">
                    <img src="/img/section/float-left-5.png" className="pc-cenetr" alt="float-left" />
                  </figure>
                  <figure className="main-pi-abso main-pic-6">
                    <img src="/img/section/float-left-6.png" className="pc-cenetr" alt="float-left" />
                  </figure>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
